### ISSUE TITLE
Initial Design

### ISSUE THREAD

**Issue by phreed** [babeloff/pixi-service-generator#1]
Create a https://www.freedesktop.org/software/systemd/man/latest/systemd.generator.html suitable for use with pixi.
Something akin to the podman  https://github.com/containers/podman/tree/main/pkg/systemd/quadlet .
This generator would examine the environments in the pixi global manifest. 
If the environment were marked with a service or daemon marker then the pixi-service-generator would, 
in the case of systemd, generate the appropriate unit files for that environment.
For example, nginx is a typical service...
Installed with:
```bash
pixi global install nginx
```

Which produces in the ~/.pixi/manifests/pixi-global.toml
```toml
[envs.nginx]
channels = ["conda-forge"]
dependencies = { nginx = "*" }
exposed = { nginx = "nginx" }
```

Information used to populate the systemd unit file would be extracted from `~/.pixi/envs/nginx/conda-meta/nginx-*.json`.
e.g., `description`, `name`, `extracted_package_dir`.
The `extracted_package_dir` would be searched for a candidate unit file, e.g., `/etc/systemd/nginx.service`
which, if present, would be the unit file (or template) used.
When not found, then the generator would use a default template  (see https://github.com/conda-forge/freva-rest-server-feedstock/blob/main/recipe/post-link.sh).
This template would be filled out using information from a `pixi-global.toml`  service element.
Something like:
```toml
[envs.nginx]
channels = ["conda-forge"]
dependencies = { nginx = "*" }
exposed = { nginx = "nginx" }
service = { status = "enabled", after = "network.target", 
            exec-start-pre = "$PREFIX/bin/nginx init",
            exec-start = "$PREFIX/bin/nginx -f $CONDA_PREFIX/etc/nginx/nginx.conf" }
```
